WCA_API = "https://www.worldcubeassociation.org/api/v0"
WCA_LIVE_API = "https://live.worldcubeassociation.org/api"

PER_PAGE = 50
LOOKBACK_DAYS = 365
ANALYSIS_LOOKBACK_DAYS = 14

DEFAULT_REQUEST_TIMEOUT = 30
COUNTRIES_REQUEST_TIMEOUT = 10
PERSON_REQUEST_TIMEOUT = 30

COUNTRIES_CACHE_TTL = 86400
PERSON_CACHE_TTL = 3600

PERSON_FETCH_WORKERS = 8
